### PR TITLE
Datetime format

### PR DESCRIPTION
**Pull request by omega**
This is somewhat related to issue #24, but not quite. It doesn't give you format strings, but it makes it possible to supply a function that changes the datestrings used via config.

I haven't updated the docs or tests, as the tests failed (I ran them via rake spec) before and after). If that is a requirement for merging, please let me know.

### CODE REVIEW

**Comment by thejefflarson** [comment]
I think you are close, I like the idea of people passing in a function that returns a specialized object, but it needs more documentation. 

I'm not so sure about setting config.humanMonths.

Could you remove the typeof checks and rely on _.isFunction too?

**Comment by thejefflarson** [comment]
Also, could you open a ticket for rake spec with exactly what the failure is?

**Comment by ashaw** [comment]
Re: spec failing, you may not have the closure-compiler gem installed. Run `rake check_dependencies` to see that you have all the deps.

**Comment by omega** [comment]
I'll see what I can figure out about documenting the changes :)

The reason for allowing changing of humanMonths, was to make writing a Norwegian version of dateStr function easier really.

**Comment by thejefflarson** [comment]
I think it would be better to just override `Intervals.dateStrings` rather than having two overlapping functions.

**Comment by omega** [comment]
The point of splitting was that being a consumer is easier if you don't have to duplicate the selection of range, and just provide the values

I did run the check deps, and json was missing, installed that and forgot to check again, will do when I have Internet again (on a weekend trip right now :)

**Comment by thejefflarson** [comment]
Makes sense, can you make the above underscore specific changes and we'll see about merging this in?

**Comment by omega** [comment]
Will do :)

**Pull request merged**
